# Generated by Django 4.0.1 on 2022-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('adress', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('zip_code', models.CharField(max_length=90)),
            ],
        ),
    ]
