# Generated by Django 4.0.1 on 2022-01-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_state_orders_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_code',
            new_name='Block_no',
        ),
    ]
