# Generated by Django 4.0.1 on 2022-01-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Block_no',
            new_name='Block',
        ),
    ]
